# Expose your documentation as JSON swagger compliant
app.swagger:
    path: /api/docs.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

app.swagger_ui:
    path: /api/docs
    controller: App\Controller\ApiDocsController
